### ISSUE TITLE
How to reference IRBEM in a publication?

### ISSUE THREAD

**Issue by claudepi** [PRBEM/IRBEM#18]
Hi all....should we have a way to reference IRBEM in the acknowledgements section and/or references of a published manuscript? The old user_guide.html said:

"If you want to fully refer to this library in publications or reports, use the following: "D. Boscher1, S. Bourdarie1, P. O'Brien2, T. Guild2,(1 ONERA-DESP, Toulouse France; 2 Aerospace Corporation, Washington DC, USA), IRBEM library V4.3, 2004-2008"."

That's obviously out of date and not going to work for AGU publications that require a DOI. So, at the very least, should we have a standard blurb that an author can stick in the acknowledgments section of their paper, perhaps even indicating which version of the library they have used?

@AntoineBrunet @mshumko @tpoiii @drsteve

**Comment by drsteve** [comment]
### Blurb
Standardized text is good here, and we probably want it up front in the README. We may also want to suggest that folks include the short hash from `git rev-parse --short HEAD` if they're working from the repo rather than a release version. I'm happy for someone else more invested in the acknowledgement to draft a blurb for some different cases (working from release, working from repo, ...).

If DOIs are requested and we haven't got a DOI for a release we may end up with folks archiving snapshots of IRBEM in different places, and who knows how that'll actually turn out... so I'd say it's a reasonably high priority to get the DOI. Folks using the SpacePy interface can cite the interface, and the version is identifiable, but if there's an IRBEM DOI I'll make sure that gets added to our citation info so users cite both codebases.


### DOI
For a DOI we'd want to turn on the Zenodo integration. (For example, see [SpacePy](https://zenodo.org/record/4472086), where the "master" doi https://doi.org/10.5281/zenodo.3252523 always points to the latest version. Other examples: [LANLGeoMag](https://zenodo.org/record/1195041); [PyForecastTools](https://zenodo.org/record/3764117))

Once the [third-party integration is turned on](https://guides.github.com/activities/citable-code/) (it needs a repo owner/admin to do that - I don't have permissions, so I can't see PRBEM/IRBEM in my repos when I log in to Zenodo) it's as simple as tagging a release in GitHub. That'll trigger an upload of the repo at that release tag and will assign a DOI. The final step is logging in to Zenodo and cleaning up the metadata so it, e.g., uses folks' names (where possible) instead of GitHub usernames, ...
It's honestly pretty trivial once the integration is turned on, so it might be useful to have a regular release schedule just to ensure there's always a recent version archived.

**Comment by mshumko** [comment]
Zenodo integration is good,  but we need to verify how often IRBEM is archived. If I correctly remember, by default the code is archived when you publish a new release, but there may be other archival triggers worth considering. 

We should consider how to version the code when we draft the new releases. For reference, the latest version on Sourceforge is 4.4.0 last modified in 2012. Some people are still [downloading it](https://sourceforge.net/projects/irbem/files/irbem/)!

If you need a citation ASAP, I already archived an older version of IRBEM [![here](https://zenodo.org/badge/DOI/10.5281/zenodo.4075396.svg)](https://doi.org/10.5281/zenodo.4075396)

**Comment by claudepi** [comment]
If we don't want to try to name/list specific contributors, then I think we keep the acknowledgement statement as simple as possible, e.g.,:

"We acknowledge the use of the IRBEM library (XXX), the latest version of which can be found at [DOI/Zenodo link]."

where the "XXX" is replaced by one of the following, depending on if you are using an official release library or a repository version of the library:

_(official release)_ 
XXX = "version X.Y.Z" where X.Y.Z is the version number of the official release that was used (https://github.com/PRBEM/IRBEM/releases)

_(repository version)_
XXX = "repository version xxxxx" where xxxxx is the output of  "$ git rev-parse --short HEAD"

**Comment by claudepi** [comment]
Circling back on this....we discussed this issue briefly today at the PRBEM business meeting at COSPAR. There were no major objections to the path I laid forth in my previous post. So, if there no additional comments/objetions from the people on this Issue, I will start working on the zenodo integration.  The zenodo/DOI will always point to the latest version and the author will indicate the specific version that they used in their blurb, as described above. 

Once I have the DOI, I will add the above blurb language to the README so it is displayed prominently at the landing page. 

Someone will also need to create an official release (probably @AntoineBrunet).

**Comment by drsteve** [comment]
Thanks @claudepi!

Just to note that Zenodo will require metadata such as authors. It'll attempt to autofill it from the commit history using the github integration, but the metadata can be changed so whoever "owns" the github integration (probably @AntoineBrunet) will have to make sure that's all right after each release. So we probably should come up with either an author list or a way of attributing authorship to "the IRBEM team" (or similar).

For the updated docs in #32 I went through the commit history and got an historical contributor list of: D. Boscher, S. Bourdarie, T. Paul O'Brien, T. Guild, D. Heynderickx, S. Morley, A. Kellerman, C. Roth, H. Evans, A. Brunet, M. Shumko, C. Lemon, S. Claudepierre, T. Nilsson. I finished the list with "and the IRBEM contributor community" as a catch-all for anyone I missed.
