### ISSUE TITLE
PRBEM/IRBEM website(s)

### ISSUE THREAD

**Issue by AntoineBrunet** [PRBEM/IRBEM#8]
As suggested in the SourceForge discussion, we should setup a website for the IRBEM documentation and the PRBEM documents that were previously hosted on the SVN repository.

I think github pages are the easy way to do so here, but if anyone has a different idea we can discuss it here.
For github pages, there is (at least) two possibilities:
  - Have a "project site" attached to the IRBEM repository. The website source can be managed in a dedicated branch or in a dedicated subdirectory of the main branch.
  - Have an "organization site" attached to the PRBEM github organization, that would be managed in a dedicated github project.
 
Of course, we can have both. For instance, we can host the PRBEM documents on the organization site and the IRBEM API documentation on the project site. This would be the most sensible option to me.

For the API documentation, right now the documentation is a static website that has to be manually edited. Setting up a github page to serve this website is as easy as moving a directory and renaming a single file (see https://antoinebrunet.github.io/IRBEM/index.html for a working example). Of course, if we want to switch to auto-generated API documentation (from source code and/or from some documentation files), it may not be good to have the generated html files on the main branch. In this case we would have to either setup a dedicated branch for the github page, or simply export the generated documentation to the organization site.

**Comment by claudepi** [comment]
Link to the SourceForge discussion Antoine notes above: https://sourceforge.net/p/irbem/discussion/876482/thread/5dbdb921f6/?limit=25#c564

I'd like to settle on a decision here for the hosting of the PRBEM documents. I don't really care what we do, so long as the current versions of the docs are available in pdf format in an obvious/prominent place. It would be nice to have editable versions of the docs in some collaborative space (Google docs), but I don't feel it's absolutely necessary. 

I'm tagging a couple people so that they can weigh in here @tpoiii @drsteve @mshumko .

After everyone weights in, @AntoineBrunet  please make a decision. Thanks!

**Comment by mshumko** [comment]
My vote is for GitHub pages. 

@claudepi if we go with the [theme](https://aksakalli.github.io/jekyll-doc-theme/docs/home/) I mentioned in the other discussion (we don't have to choose this theme specifically), the document text will be written in markdown and saved in a `docs` folder in this repo. Is that a collaborative space in your opinion?

**Comment by claudepi** [comment]
@mshumko I personally feel that the PRBEM standard documents should be preserved in MS Word-like format. I think converting them to markdown is not a good idea. The documents need to be able to handle equations, etc... so MS-Word or Google doc or something similar is probably best.

**Comment by claudepi** [comment]
For reference, these are the PRBEM standard docs in question: https://sourceforge.net/p/irbem/code/HEAD/tree/docs/

**Comment by AntoineBrunet** [comment]
Hello all, sorry for the long response time!

I've setup a small demo github page (see here https://antoinebrunet.github.io/), using jekylls as recommanded by github. We can easily add pages (accessible from the menu) and news (listed on the home page), by adding markdown files to the corresponding repository. 

If it's okay for everyone, I'll setup the repository on the PRBEM github organization, and then we can manage the website from there.

As for editing the documents themselves, if we want to stick to the MS doc format, I think it's better to manage them outside (like you said @claudepi we could do it on google doc or something similar). Although, I think the documents would be better managed on Github if we switch to markdown or LaTeX (both can support math I think). For instance the [HAPI standard is written in markdown on Github](https://github.com/hapi-server/data-specification).

**Comment by claudepi** [comment]
@AntoineBrunet  the PRBEM demo webpage looks great to me! Simple and straightforward. Easy to find the documents and relevant information.  I vote for moving forward in this manner. 

On the latter point, I agree that management of the documents is better in github if they are in markdown or Latex, but they are also harder to edit if that's the case. Some people may not feel comfortable (or know how to) editing them in markdown or Latex.  Plus someone also has to convert them over to Latex, which will take a fair bit of work and has the potential to introduce errors. So I'm not really sure what the best solution is here. For now, I think if we can just host the word/pdf docs like you have done with the demo webpage, that will be good.

**Comment by drsteve** [comment]
The _standards_ documents are probably best left as hosted `.doc` and `.pdf` files. I think the key here is that the older standards documents are, and should be, static. There's really nothing to be gained from converting them. If new standards documents are being developed then that could be done as markdown or latex through github, but my guess is that @claudepi is right about the general comfort levels for that. Honestly, development of new standards  is likely to be done through a working group possibly including real-time development. So I'd suggest that if/when that happens the standards documentation is developed and iterated on using something like Google Docs/Word Online/Overleaf, and the output is then stored as a static file just like the current versions. 

The demo organization site set up by @AntoineBrunet looks good. Straightforward, on brand, etc. And I'm very supportive of the statement in his first post here "_For instance, we can host the PRBEM documents on the organization site and the IRBEM API documentation on the project site. This would be the most sensible option to me._"  Since bringing the API documentation into the modern age and making it more maintainable is going to be a chore, I'm going to suggest putting that to one side (for now) and pressing on with getting the organization site up with the standards documents since they're quite tricky to find otherwise!

**Comment by mshumko** [comment]
@AntoineBrunet I agree with everyone that your docs look great! I only worked with the IRBEM docs, so I can't comment more on the standards documents.

Once we revisit the documentation format question, we can try out [pandoc](https://pandoc.org/) to convert between Word, markdown, and LaTeX. This could allow us to edit a Word doc and use GitHub Actions to convert it to Markdown and update the online docs.

**Comment by VinniDoddu** [comment]
I find the website also great, and I fully agree with @drsteve: do not forget that PRBEM and IRBEM are also hosting old fortran guys who are just new to python. So just imagine what it would be for them if they have to learn LaTeX at such an old age....

**Comment by AntoineBrunet** [comment]
Hi all,
I've put on the website on the https://github.com/PRBEM/PRBEM.github.io repository, so it is now accessible from https://prbem.github.io . To manage this website, we can have a "webmaster" github team managing the repository, would anyone be interested to be part of this? Of course, anyone can submit PR or raise issues on the website project page, I think it's just easier if more than one person can commit change.

**Comment by mshumko** [comment]
I am interested in contributing the docs when I can. Please add me to the
webmaster github team.

____________________
Mykhaylo (Mike) Shumko
Website <https://mshumko.github.io/>

**Comment by AntoineBrunet** [comment]
@mshumko Ok you are now on the webmaster team.

Since we have setup a dedicated website repository and the user manual is also online, I guess we can close this issue for now. If at some point we update to documentation format, we'll probably open a new dedicated issue.

Thank you all for your comments and remarks.
